name: Build macOS

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-macos-metal:
    name: Build macOS (Apple Silicon + Metal)
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Install dependencies
        run: |
          brew install cmake
          
      - name: Build llama.cpp with Metal
        run: |
          make build-llama-metal
          
      - name: Build inference service
        run: |
          make build-all
          
      - name: Test build
        run: |
          ./bin/inference-server --help || true
          ./bin/nats-chat --help || true
          
      - name: Package macOS release
        run: |
          mkdir -p dist/macos-arm64
          cp bin/inference-server dist/macos-arm64/
          cp bin/nats-chat dist/macos-arm64/
          cp -r envs dist/macos-arm64/
          cp -r examples dist/macos-arm64/
          cp -r scripts dist/macos-arm64/
          cp -r data dist/macos-arm64/
          cp Makefile dist/macos-arm64/
          cp README.md dist/macos-arm64/
          cp LICENSE dist/macos-arm64/
          cd dist && zip -r inference-service-macos-arm64-metal.zip macos-arm64/
          
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-arm64-metal
          path: dist/inference-service-macos-arm64-metal.zip